### ISSUE TITLE
로컬에선 마이크가 잘 사용되었는데 GCP로 배포되니 마이크가 동작되지 않음 

### ISSUE THREAD

**Issue by IChanHui** [resonance-ai/pulse9#13]
콘솔에 보이스 관련 콘솔로그가 전혀 띄워지지않음

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/89351104-238a-40e0-9483-c565f12848f3">

**Comment by leechanwoo** [comment]
### http에서 마이크 권한 설정 허용

**chrome://flags/#unsafely-treat-insecure-origin-as-secure**

<img width="733" alt="image" src="https://github.com/user-attachments/assets/f59f0b9a-6ba7-4a5b-98b1-626a71cc795c">
