### ISSUE TITLE
ui-custom 웹소켓, 세션 오류 

### ISSUE THREAD

**Issue by IChanHui** [resonance-ai/pulse9#6]
오류
첫 화면에서 start session으로 시작하든 네이게이션 바로 아바타를 선택하든 모두 잘 실행되지만 웹소켓을 연결할 수 없다는 오류와 아바타 세션 에러가 동시에 콘솔로 올라옴. 기존에 존재하던 startSession 함수랑 추가로 복사해서 만든 changeAvatar 함수에서 무언가 충돌로 추측됨

`WebSocket connection to 'wss://api.heygen.com/v1/ws/streaming.chat?session_id=79be175b-821e-11ef-a7d7-c6753ff47364&session_token=eyJ0b2tlbiI6ICIxNDhjZWVkZjJkZDg0NDRhOWNhYjdjYmU2YmVkZjliNCIsICJ0b2tlbl90eXBlIjogInNhX2Zyb21fdHJpYWwiLCAiY3JlYXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English' failed:`

`Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event`

`Error starting avatar session: Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event`

<img width="399" alt="image" src="https://github.com/user-attachments/assets/6a6a84fe-0fb1-43b5-90d7-65474f847b67">

**Comment by leechanwoo** [comment]
에러 내용을 좀 보여줘야함

**Comment by leechanwoo** [comment]
```shell
WebSocket connection to 'wss://api.heygen.com/v1/ws/streaming.chat?session_id=79be175b-821e-11ef-a7d7-c6753ff47364&session_token=eyJ0b2tlbiI6ICIxNDhjZWVkZjJkZDg0NDRhOWNhYjdjYmU2YmVkZjliNCIsICJ0b2tlbl90eXBlIjogInNhX2Zyb21fdHJpYWwiLCAiY3JlYXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English' failed:

Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event

Error starting avatar session: Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event
```

**Comment by leechanwoo** [comment]
`WebSocket connection to 'wss://api.heygen.com/v1/ws/streaming.chat?session_id=79be175b-821e-11ef-a7d7-c6753ff47364&session_token=eyJ0b2tlbiI6ICIxNDhjZWVkZjJkZDg0NDRhOWNhYjdjYmU2YmVkZjliNCIsICJ0b2tlbl90eXBlIjogInNhX2Zyb21fdHJpYWwiLCAiY3JlYXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English' failed:

Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event

Error starting avatar session: Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event`

**Comment by leechanwoo** [comment]
```
WebSocket connection to 'wss://api.heygen.com/v1/ws/streaming.chat?session_id=79be175b-821e-11ef-a7d7-c6753ff47364&session_token=eyJ0b2tlbiI6ICIxNDhjZWVkZjJkZDg0NDRhOWNhYjdjYmU2YmVkZjliNCIsICJ0b2tlbl90eXBlIjogInNhX2Zyb21fdHJpYWwiLCAiY3JlYXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English' failed:

Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event

Error starting avatar session: Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://api.heygen.com/v1/ws/streaming.chat?session_…YXRlZF9hdCI6IDE3MjgwMjUyODZ9&stt_language=English', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 81376.79999995232type: "error"[[Prototype]]: Event
```

**Comment by leechanwoo** [comment]
에러 내용 좀 잘 넣는 방법이 없을까 영 시원찮네

**Comment by leechanwoo** [comment]
<img width="520" alt="image" src="https://github.com/user-attachments/assets/737d16d0-aa29-4d11-a467-73d82f5b412a">

지금 보아하니 websocket 오류인데, voice chat 하기위한 web socket 연결에 문제가 있는 듯. 지금 뭔가 음성 채팅이 잘 안되는 상태일 듯.

```typescript
    try {
      console.log('[LOG] Creating start Avatar');
      const res = await avatar.current.createStartAvatar({
        quality: AvatarQuality.Low,
        avatarName: selectedAvatarId,
        knowledgeId: knowledgeId, // Or use a custom `knowledgeBase`.
        voice: {
          rate: 1.5, // 0.5 ~ 1.5
          emotion: VoiceEmotion.EXCITED,
        },
        language: "English",
      });
      console.log('[LOG] Avatar Created');

      setData(res);
      console.log('[LOG] setData(res)', res);
      // default to voice mode
      await avatar.current?.startVoiceChat();
      console.log('[LOG] startVoiceChat()')
      setChatMode("voice_mode");
      
    } catch (error) {
      console.error("Error starting avatar session:", error);
    } finally {
      setIsLoadingSession(false);
    }
  }
```

**Comment by leechanwoo** [comment]
<img width="905" alt="image" src="https://github.com/user-attachments/assets/11becd95-46f5-4207-9420-8476a19411bd">

<img width="517" alt="image" src="https://github.com/user-attachments/assets/0b987452-0a7b-4df2-9615-affe98a9b9f3">

Voice mode 선택하면 에러나면서 안되는 상황.

**Comment by leechanwoo** [comment]
Demo 원본에서 가져온 `InteractiveAvatar.tsx` 소스 코든데 지금 코드랑 너무 다름 
특히 `import StreamingAvatarTextInput from "./StreamingAvatarTextInput";`  얘가 안보임

```typescript
import {
    Configuration,
    NewSessionData,
    StreamingAvatarApi,
  } from "@heygen/streaming-avatar";
  import {
    Button,
    Card,
    CardBody,
    CardFooter,
    Divider,
    Input,
    Spinner,
    Tooltip,
  } from "@nextui-org/react";
  import { useChat } from "ai/react";
  import OpenAI from "openai";
  import { useEffect, useRef, useState } from "react";
  import StreamingAvatarTextInput from "./StreamingAvatarTextInput";
  import {
    Camera,
    Microphone,
    MicrophoneSlash,
    MicrophoneStage,
    Record,
  } from "@phosphor-icons/react";
  import clsx from "clsx";
  
  const openai = new OpenAI({
    apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
    dangerouslyAllowBrowser: true,
  });
  
```
